name: Build u-boot-boughboot
run-name: ${{ inputs.bootorder}}
on:
  workflow_dispatch:
    inputs:      
      uboot_repo:
        required: true
        type: choice
        description: u-boot git repo
        options: 
        - https://source.denx.de/u-boot/u-boot
        - custom_repo
      uboot_repo_custom:
        description: custom u-boot git repo
        required: false
        type: string
      uboot_ref:
        required: true
        type: choice
        description: u-boot ref
        options: 
        - v2024.01
        - v2023.10
        - master
        - custom_ref
      uboot_ref_custom:
        description: custom u-boot ref
        required: false
        type: string


jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: 
          [
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
              "build": "boughboot",
            }
          ]

    steps:
      - name: Checkout Opi5-u-boot-custom
        uses: actions/checkout@v3
        with:
          repository: ArchemedIan/Opi5-u-boot-boughboot
          ref: main
          path: .

      - name: Build "${{ matrix.boards.config }}." variant "${{ matrix.boards.build }}"
        run: |
          cd ${{ matrix.boards.build }}
          chmod a+x ./build.sh 
          ./build.sh "${{ inputs.uboot_ref }}" "${{ inputs.uboot_repo }}" "${{ matrix.boards.config }}" "${{ inputs.uboot_ref_custom }}" "${{ inputs.uboot_repo_custom}}" "${{ matrix.boards.name }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: u-boot-${{ matrix.boards.build }}-${{ inputs.uboot_ref }}-${{ matrix.boards.name }}
          path: ${{ matrix.boards.build }}/out/*
